### ISSUE TITLE
Use of unknown -s option to which command

### ISSUE THREAD

**Issue by dmeranda** [SchemaPlus/schema_dev#11]
Inside ruby_selector.rb there are a couple places where it invokes the system `which` command but with an unknown option `-s`.  At least that is not an option supported by the [GNU which](https://savannah.gnu.org/projects/which/) command.  This causes that which command to always fail and report an error.

```
$ schema_dev bundle install


*** ruby 2.2.3 - activerecord 4.2 - db mysql2 [1 of 3]

which: invalid option -- 's'
which: no chruby-exec in (...)
which: invalid option -- 's'
which: no rvm in (...)
```

By chance was this meant to be the `--skip-alias` option?

**Comment by ronen** [comment]
On OS X `-s` is the "silent" option:
>    -s      No output, just return 0 if any of the executables are found, or 1 if none are found.

I didn't realize that it's not universal.

Probably the better option would be to use the [which_works](https://github.com/AlphaHydrae/which_works) gem.  Would you be willing to put together a PR to fix it?
