### ISSUE TITLE
Trusty Travis environment does not allow 'travis' user to create databases

### ISSUE THREAD

**Issue by lowjoel** [SchemaPlus/schema_dev#20]
See https://travis-ci.org/SchemaPlus/schema_plus_foreign_keys/jobs/266638962

The current workaround is to use the 'root' user instead in the environment variable. Ideally, the `create_databases` task should use root to create the database and continue using `travis` to run tests.

**Comment by urkle** [comment]
no longer an issue as this gem will be dropping support from Travis CI and moving to github actions
